import type { Metadata } from "next";
import { Inter, Roboto_Mono, Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
const noto_Kufi_Arabic = Noto_Kufi_Arabic({ subsets: ["latin"], weight: "300" })
const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sayed's Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${noto_Kufi_Arabic.className}`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
